version: '3.8'
services:
  frontend:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      bash -c "npm install -g create-react-app &&
               if [ ! -d ./node_modules ]; then
                 if [ ! -f ./package.json ]; then
                   create-react-app . &&
                   npm install axios redux react-redux;
                 else
                   npm install;
                 fi
               fi &&
               npm start"

  backend:
    image: node:latest
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      bash -c "if [ ! -f ./package.json ]; then
                rm -rf * &&
                yes '' | npx create-next-app@latest . --use-npm --ts &&
                npm install axios;
              else
                npm install;
              fi &&
              npm run dev"
